// File generated by FlutterFire CLI / Manual configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJhOdaohs_MDguLilIk3gnE-jGQNvNi94',
    appId: '1:145497380552:web:b917427466b676664177fd',
    messagingSenderId: '145497380552',
    projectId: 'studentinsight-ai-b7fbe',
    authDomain: 'studentinsight-ai-b7fbe.firebaseapp.com',
    storageBucket: 'studentinsight-ai-b7fbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhOdaohs_MDguLilIk3gnE-jGQNvNi94',
    appId: '1:145497380552:android:b917427466b676664177fd',
    messagingSenderId: '145497380552',
    projectId: 'studentinsight-ai-b7fbe',
    storageBucket: 'studentinsight-ai-b7fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJhOdaohs_MDguLilIk3gnE-jGQNvNi94',
    appId: '1:145497380552:ios:b917427466b676664177fd',
    messagingSenderId: '145497380552',
    projectId: 'studentinsight-ai-b7fbe',
    storageBucket: 'studentinsight-ai-b7fbe.firebasestorage.app',
    iosBundleId: 'com.assetmanager.assetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJhOdaohs_MDguLilIk3gnE-jGQNvNi94',
    appId: '1:145497380552:ios:b917427466b676664177fd',
    messagingSenderId: '145497380552',
    projectId: 'studentinsight-ai-b7fbe',
    storageBucket: 'studentinsight-ai-b7fbe.firebasestorage.app',
    iosBundleId: 'com.assetmanager.assetManager',
  );
}
